
name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: deploy
        run: now --token ${{ secrets.ZEIT_TOKEN }}
